export const START_FETCH_COMPANY_DETAILS = "START_FETCH_COMPANY_DETAILS";
export const FETCH_COMPANY_DETAILS_SUCCESS = "FETCH_COMPANY_DETAILS_SUCCESS";
export const FETCH_COMPANY_DETAILS_FAILURE = "FETCH_COMPANY_DETAILS_FAILURE";
export const RESET = "RESET";
